#!/usr/bin/python3
# a Python script to add eneumerate to Markdown Files
import re, sys, os

first=0
second=0
third=0

fileName=sys.argv[1]
fileBak=fileName+".bak"
From_file=open(fileName)           #txt文件位置
f=open(fileBak,'w')             #生成的文件名字

for each_line in From_file:
	if(re.search("^# ",each_line)):
		first+=1
		second=0
		third=0
		new_line=re.sub("^# ","# "+str(first)+" ",each_line)
		if(re.search("^# \d ",each_line)):
			f.writelines(each_line)
		else:
			f.writelines(new_line)
	elif(re.search("^## ",each_line)):
		second+=1
		third=0
		new_line=re.sub("^## ","## "+str(first)+"."+str(second)+" ",each_line)
		if(re.search("^## \d\.\d ",each_line)):
			f.writelines(each_line)
		else:
			f.writelines(new_line)
	elif(re.search("^### ",each_line)):
		third+=1
		new_line=re.sub("^### ","### "+str(first)+"."+str(second)+"."+str(third)+" ",each_line)
		if(re.search("^### \d\.\d\.\d ",each_line)):
			f.writelines(each_line)
		else:
			f.writelines(new_line)
	else:
		f.writelines(each_line)

f.close()
From_file.close()


# change file name
os.remove(fileName)
os.rename(fileBak, fileName)
