#!/usr/bin/python3
import re, sys, os

first = 0
second = 0
third = 0

fileName = sys.argv[1]
targetPic = "notDefined"  # default not change
originPic = "notDefined"  # default not change

if len(sys.argv) > 2:
    targetPic = sys.argv[2]

if len(sys.argv) > 3:
    originPic = sys.argv[3]

fileBak = fileName + ".bak"
From_file = open(fileName)  # txt文件位置
f = open(fileBak, "w")  # 生成的文件名字


# change subfix to targetPic
# change sentence if target image type miss match source image type
def change(sentence, targetPic):
    return sentence + "." + targetPic + ")\n"


# ![1 bit predictor](https://s2.loli.net/2023/03/15/ABW43YhqrETUZgJ.png)

# print("targetPic= " , targetPic)
# print(type(targetPic)) # argv value is string

for each_line in From_file:
    ss = re.split("\.", each_line)
    sentence = each_line
    # change sentence if target image type miss match source image type
    if len(ss) > 1:
        if re.search("!\[.*\]\(http", each_line) == None:  # don't change url
            sourcePic = ss[1][:-3]
            # print("ss= ",ss[1])
            # print("source= ",sourcePic)
            print(
                "target ", targetPic, ", source: ", sourcePic, ", origin: ", originPic
            )
            if targetPic != sourcePic and targetPic != "notDefined":
                if originPic == "notDefined":
                    sentence = change(ss[0], targetPic)
                else:
                    if sourcePic == originPic:  # all subfix to target_subfix
                        sentence = change(ss[0], targetPic)
                    elif sourcePic != originPic:  # only origin_subfix to target_subfix
                        sentence = change(ss[0], sourcePic)
    f.writelines(sentence)

f.close()
From_file.close()


# change file name

# os.remove(fileName)
# os.rename(fileBak, fileName)
