#!/usr/bin/python3

import random
from datetime import datetime

random.seed(datetime.now().timestamp())
select = random.randint(1,10)
if(select % 2 == 0):
    print("what you wish is going to happen")
else:
    print("what you wish is not going to happen")
